/**
 * Skill: open-release-pr
 *
 * Push branch to origin and open PR via gh CLI.
 */

import { execa } from "execa";
import type { BumpProposal } from "../propose-bump";

export interface OpenPRInput {
  branchName: string;
  version: string;
  proposals: BumpProposal[];
  verdict: "go" | "go-with-warnings" | "no-go";
  warnings?: string[];
  reason: string;
}

export interface OpenPROutput {
  prNumber: number;
  prUrl: string;
}

function buildPRBody(input: OpenPRInput): string {
  const verdictIcon = { go: ":green:", "go-with-warnings": ":yellow:", "no-go": ":red:" }[input.verdict];

  const proposalTable = [
    "| Package | Bump |",
    "|---|---|",
    ...input.proposals.map((p) => `| \`${p.package}\` | ${p.bump} |`),
  ].join("\n");

  const warningsBlock = input.warnings && input.warnings.length > 0
    ? `\n## :warning: Warnings\n` + input.warnings.map((w) => `- ${w}`).join("\n")
    : "";

  return [
    `# Release Proposal: v${input.version}`,
    ``,
    `**Verdict**: ${verdictIcon} ${input.verdict.toUpperCase()}`,
    `**Reason**: ${input.reason}`,
    ``,
    `## Changes`,
    proposalTable,
    warningsBlock,
    ``,
    `## Reviewer Checklist`,
    `- [ ] Version bumps are correct`,
    `- [ ] CHANGELOG entries are accurate`,
    `- [ ] No unexpected package changes`,
    `- [ ] Pre-publish check verdict acceptable`,
    `- [ ] OK to publish to npm after merge`,
    ``,
    `## What happens after merge`,
    `1. CI runs full pre-publish-check`,
    `2. If pass: publish packages to npm with provenance`,
    `3. Tag release: \`v${input.version}-phase-5\``,
    `4. Smoke test, then notify on release issue`,
    `5. (Manual) Trigger Pro release via \`trigger-pro.yml\``,
    ``,
    `## Audit`,
    `This PR was generated by \`release-lead\` agent. See \`.orqenix/release-audit.log\` for actions.`,
    ``,
    `cc @milosaysyolo`,
  ].join("\n");
}

export async function run(input: OpenPRInput): Promise<OpenPROutput> {
  await execa("git", ["push", "-u", "origin", input.branchName]);

  const body = buildPRBody(input);
  const { stdout } = await execa("gh", [
    "pr",
    "create",
    "--title",
    `chore(release): v${input.version} proposal`,
    "--body",
    body,
    "--label",
    "release-proposal",
    "--label",
    "needs-human-approval",
    "--reviewer",
    "milosaysyolo",
  ]);

  const urlMatch = stdout.match(/https:\/\/github\.com\/[^/]+\/[^/]+\/pull\/(\d+)/);
  if (!urlMatch) {
    throw new Error(`Could not parse PR URL from gh output: ${stdout}`);
  }
  const prUrl = urlMatch[0];
  const prNumber = parseInt(urlMatch[1], 10);

  return { prNumber, prUrl };
}
